from taskee import colors

CANCELLED = "CANCELLED"
CANCEL_REQUESTED = "CANCEL_REQUESTED"
RUNNING = "RUNNING"
COMPLETED = "COMPLETED"
FAILED = "FAILED"
READY = "READY"

FINISHED = [COMPLETED, FAILED, CANCELLED]
ACTIVE = [READY, RUNNING]
UNSUCCESSFUL = [FAILED, CANCELLED]

STATE_COLORS = {
    CANCELLED: colors.COLOR_ERROR,
    CANCEL_REQUESTED: colors.COLOR_ERROR,
    RUNNING: colors.COLOR_INFO,
    COMPLETED: colors.COLOR_SUCCESS,
    FAILED: colors.COLOR_ERROR,
    READY: colors.COLOR_INFO,
}
