CANCELLED = "CANCELLED"
RUNNING = "RUNNING"
COMPLETED = "COMPLETED"
FAILED = "FAILED"
READY = "READY"

FINISHED = [COMPLETED, FAILED, CANCELLED]
ACTIVE = [READY, RUNNING]
UNSUCCESSFUL = [FAILED, CANCELLED]
